---
- name: restart_nrpe
  tags: nagios,nrpe
  ansible.builtin.service:
    name: "{{ nrpe_service }}"
    state: restarted

- name: restart_qemu_agent
  tags: qemu,qemu-agent
  ansible.builtin.service:
    name: "{{ qemu_agent_service }}"
    state: restarted

- name: restart_ufw
  tags: ufw
  ansible.builtin.service:
    name: ufw
    state: restarted
