- name: users | root | ensure account is locked
  ansible.builtin.user:
    name: root
    password_lock: yes

- name: users | root | create config directories
  ansible.builtin.file:
    path: /root/{{ item.dir }}
    state: directory
    owner: root
    ansible.builtin.group: root
    mode: 0700
  with_items:
      - { dir: '.vim' }
      - { dir: '.vim/colors' }
  tags: dotfiles

- name: users | root | copy dotfiles
  ansible.builtin.copy:
    src: users/root/{{ item.src }}
    dest: /root/{{ item.dest}}
    owner: root
    ansible.builtin.group: root
    mode: 0600
  with_items:
      - { src: 'bash/bashrc', dest: '.bashrc' }
      - { src: 'bash/bash_profile', dest: '.bash_profile' }
      - { src: 'bash/profile', dest: '.profile' }
      - { src: 'tmux/tmux.conf', dest: '.tmux.conf' }
      - { src: 'vim/vimrc', dest: '.vimrc' }
      - { src: 'vim/xoria256.vim', dest: '.vim/colors/xoria256.vim' }
      - { src: 'zsh/zshrc', dest: '.zshrc' }
  tags: dotfiles
