# As of 2020-06-18, lutris is not available on debian
- name: software | lutris | install ppa
  tags: gaming,lutris
  ansible.builtin.apt_repository:
    repo: 'ppa:lutris-team/lutris'
    state: present
  when:
    - ansible_distribution in ["Pop!_OS", "Ubuntu"]
    - lutris is defined
    - lutris == true

- name: software | lutris | install package
  tags: gaming,lutris
  ansible.builtin.package:
    state: latest
    name: lutris
  when:
    - ansible_distribution in ["Archlinux", "Pop!_OS", "Ubuntu"]
    - lutris is defined
    - lutris == true
