- name: software | signal | install package
  tags: packages,flatpak,signal,workstation-packages
  become_user: jay
  community.general.flatpak:
    name: org.signal.Signal
    method: user
    state: present
  when: signal is defined and signal == true

- name: software | signal | enable autostart
  tags: packages,flatpak,signal,workstation-packages
  ansible.builtin.file:
    src: /home/jay/.local/share/flatpak/exports/share/applications/org.signal.Signal.desktop
    dest: /home/jay/.config/autostart/org.signal.Signal.desktop
    owner: jay
    ansible.builtin.group: jay
    state: link
  when: signal is defined and signal == true
