- name: software | install workstation distribution packages
  tags: packages,workstation-packages
  ansible.builtin.package:
    name: solaar
    state: latest

- name: software | make sure solaar doesn't autostart
  ansible.builtin.file:
    path: /etc/xdg/autostart/solaar.desktop
    state: absent
