- name: software | vagrant | install binary
  ansible.builtin.unarchive:
    src: https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755
    owner: root
    ansible.builtin.group: root
  when:
    - vagrant is defined
    - vagrant == true
