- name: software | vivaldi | add repository key
  tags: packages,vivaldi
  ansible.builtin.apt_key:
    url: https://repo.vivaldi.com/stable/linux_signing_key.pub
    state: present
  when:
    - ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
    - vivaldi is defined
    - vivaldi == true

- name: software | vivaldi | check if repository exists
  ansible.builtin.stat:
    path: /etc/apt/sources.list.d/vivaldi.list
  register: vivaldi_repo_file

- name: software | vivaldi | add repository
  tags: packages,vivaldi
  ansible.builtin.apt_repository:
    repo: "deb https://repo.vivaldi.com/stable/deb/ stable main"
    state: present
    filename: vivaldi
  when:
    - ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
    - vivaldi is defined
    - vivaldi == true
    - vivaldi_repo_file.stat.exists == False

- name: software | vivaldi | install package
  tags: packages,vivaldi
  ansible.builtin.apt:
    name: vivaldi-stable
    state: latest
  when:
    - ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
    - vivaldi is defined
    - vivaldi == true
